### ISSUE TITLE
Surface Dial Suggestion

### ISSUE THREAD

**Issue by androidotai** [Microsoft/Windows-tutorials-inputs-and-devices#1]
Hello Microsoft Team.

Probably this might not be the suitable place for me to communicate with y'all, but I have few suggestions to improve Surface Dial reliability.
First, for none Microsoft Surface user, my suggestion is to enable the option to force on-screen display of context menu, so that user can know current mode of their Surface Dial. Cuz, currently there is no option to enable it, and we as a user don't know what current mode is for the surface input as mode can be different depends on specific application. 

The other suggestions as below:

- Adjust Intensity for scrolling left and right
- Double click action
- Triple click action
- Hold Click and rotate action
- Context Menu (radial menu) always Display (With Legend View of Action per event, or display in task bar))
- Move context menu everywhere
- Display on top
- Display in which screen (multiple displays)
- Always Focus on specific application (Case of Multiple Monitor, multiple running program))
- More Detail key (e.g.: Windows Key, media Key, Hold and release Key Option))
- Separate between global context menu, and specific app context menu
- Easily customize icon for custom action
- differentiate numpad key or not.
- Support for other OS.
- Surface Dial as on-screen virtual Keyboard.
- Surface Dial emulator

Hope y'all can consider my suggestion as from my perspective, this accessories can help many people improve their productivity.

Thanks.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for you suggestions, @androidotai! You're correct, this repo is intended for doc suggestions, bug reports, PR fixes, etc. For product feedback you can try the "This product" button to the left of the "This page" button at the bottom of any of our topics. Specifically, https://docs.microsoft.com/en-us/windows/apps/design/input/windows-wheel-interactions#feedback for the Dial.
